version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    container_name: backend
    volumes:
       - ./backend:/usr/src/app/backend
       - /usr/src/app/backend/node_modules
    depends_on:
       - dockerDB
  dockerDB:
    image: mongo
    container_name: dockerDB
    ports:
     - "27017:27017"
    volumes:
     - ./data:/data/db
volumes:
  mongodata: